// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createRow = `-- name: CreateRow :exec
INSERT INTO sex (month, year) VALUES (?, ?)
`

type CreateRowParams struct {
	Month int64
	Year  int64
}

func (q *Queries) CreateRow(ctx context.Context, arg CreateRowParams) error {
	_, err := q.db.ExecContext(ctx, createRow, arg.Month, arg.Year)
	return err
}

const deleteLast = `-- name: DeleteLast :exec
DELETE FROM sex
WHERE id = (SELECT MAX(id) FROM sex)
`

func (q *Queries) DeleteLast(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLast)
	return err
}

const getAllByMonth = `-- name: GetAllByMonth :one
SELECT COUNT(*) FROM sex
WHERE month = ?
`

func (q *Queries) GetAllByMonth(ctx context.Context, month int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllByMonth, month)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllByYear = `-- name: GetAllByYear :one
SELECT COUNT(*) FROM sex
WHERE year = ?
`

func (q *Queries) GetAllByYear(ctx context.Context, year int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllByYear, year)
	var count int64
	err := row.Scan(&count)
	return count, err
}
